SinusCsharp/Models/Cart.cs
using Microsoft.EntityFrameworkCore;

namespace SinusCsharp.Models
{
   public class Cart
   {
        public int ProductId { get; set; }
        public int Quantity { get; set; } = 1;

        public Product? Product { get; set; }


    }
 
}

SinusCsharp/Controllers/CartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Data.Services;
using SinusCsharp.Models;


namespace SinusCsharp.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICartService _cartService;

        public CartsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor,
            ICartService cartService)
        {
            _cartService = cartService;
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Carts
        public IActionResult Index()
        {
            List<Cart>? cartList = new();
            if(HttpContext.Request.Cookies.ContainsKey("Cart")) 
            {
                var json = Request.Cookies["Cart"];
                cartList = JsonSerializer.Deserialize<List<Cart>>(json);
            } 

            return View(cartList);
        }

        // GET: Carts/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<Cart> cartList = GetCartListFromCookie();
            var item = cartList.FirstOrDefault(i => i.ProductId == id);
            
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ProductId,Quantity")] Cart cart)
        {
            if (id != cart.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                List<Cart> cartList = GetCartListFromCookie();
                cartList = _cartService.UpdateQuantityOfAProduct(cartList, cart);
                AddCartListToCookie(cartList);
  
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<Cart> cartList = GetCartListFromCookie();

            var cart = cartList.FirstOrDefault(m => m.ProductId == id);

            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            var cartList = GetCartListFromCookie();

            if (cartList != null)
            {
                cartList.RemoveAll(i => i.ProductId == id);
            }
            AddCartListToCookie(cartList);

            return RedirectToAction(nameof(Index));
        }

        //Get
        public IActionResult Buy(int id)
        {

            Product? product = _context.Product.FirstOrDefault(p => p.ProductId == id);

            Cart cartobject = new() { ProductId = id, Quantity = 1, Product = product };

            List<Cart>? cartList = GetCartListFromCookie();

            cartList = _cartService.AddProductToCart(cartList, cartobject);

            AddCartListToCookie(cartList);

            return RedirectToAction(nameof(Index));
        }
        //
        public IActionResult Pay(int customerId)
        {
            if (!HttpContext.Request.Cookies.ContainsKey("Customer"))
            {
                CookieOptions cookieCustomer = new CookieOptions();
                cookieCustomer.Expires = DateTime.UtcNow.AddMinutes(5);
                cookieCustomer.Path = "/"; //Also defaultvalue. Will be accessible "everywhere"

                // https://code-maze.com/csharp-object-into-json-string-dotnet/
                //var jsonString = JsonSerializer.Serialize(customerId);

                Response.Cookies.Append("Customer", customerId.ToString(), cookieCustomer);
           
            }
            List<Cart> cartList = GetCartListFromCookie();
            return View(cartList);
        }
        public IActionResult Confirmation()
        {
            // Get and send Customer,Order and Productlist to view
            // Partialview only return the Confirmation view without the layout
            return PartialView();
        }


        public List<Cart> GetCartListFromCookie()
        {
            //Unserialize cartList from Cookie
            var json = Request.Cookies["Cart"];
            List<Cart>? cartList = JsonSerializer.Deserialize<List<Cart>>(json);
            return cartList;
        }
        private void AddCartListToCookie(List<Cart> cartList)
        {
            //Serialize new cartList
            var jsonString = JsonSerializer.Serialize(cartList);
            Response.Cookies.Append("Cart", jsonString);
        }



        // Not needed but nice example of try-catch specifik sqlException
        /*public async Task<IActionResult> Buy2(int id)
        {

            if (ModelState.IsValid)
            {
                Cart cart = new Cart() { ProductId = id, Quantity = 1};
                try
                {
                    _context.Add(cart);
                    await _context.SaveChangesAsync();  
                }
                catch (DbUpdateException ex) 
                {
                    if (ex.InnerException is SqlException sqlException)
                    {
                        // Check if the error code indicates a unique key constraint violation
                        if (sqlException.Number == 2627 || sqlException.Number == 2601)
                        {
                            //Only update the specifik field qty
                            var cartItem = _context.Cart.SingleOrDefault(x => x.ProductId == id);
                            int qty = cartItem.Quantity +1;
         
                            _context.Cart.Where(x => x.ProductId == id)
                                .ExecuteUpdate(q => q.SetProperty(p => p.Quantity, qty));
                        }
                        else
                        {
                            // Handle other SQL exceptions
                            // For example:
                            Console.WriteLine("An SQL exception occurred with error code " + sqlException.Number);
                        }
                    }

                }
                
            }
            return RedirectToAction("Index", "Products");
        } */
    }
}

SinusCsharp/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Models;

namespace SinusCsharp.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
              return _context.Customer != null ? 
                          View(await _context.Customer.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Customer'  is null.");
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,PhoneNumber,Address,City,Zip")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Email,PhoneNumber,Address,City,Zip")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Customer == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Customer'  is null.");
            }
            var customer = await _context.Customer.FindAsync(id);
            if (customer != null)
            {
                _context.Customer.Remove(customer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Customers by Email
        public async Task<IActionResult> GetCustomer(string? Email)
        {
            if (Email == null || _context.Customer == null)
            {              
                return View("CheckOut");
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.Email == Email);
            if (customer == null)
            {
                ViewBag.Message = "No Customer with that email";
                return View("CheckOut");
            }

            return View("Details", customer);
        }

        public IActionResult CheckOut() 
        { 
            return View();
        }

        private bool CustomerExists(int id)
        {
          return (_context.Customer?.Any(e => e.CustomerId == id)).GetValueOrDefault();
        }
    }
}

SinusCsharp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Models;

namespace SinusCsharp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.Customer);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Orders/Create
        public async Task<IActionResult> Create()
        {
            //var id = Request.Cookies["Customer"];
            int customerId = int.Parse(Request.Cookies["Customer"]);
            if(customerId != 0)
            {
                Order order = new() {CustomerId = customerId, OrderDate = DateTime.Now, Shipped = true};
                _context.Add(order);
                await _context.SaveChangesAsync();
                int orderId = order.OrderId; //Get last inserted Id
                TempData["OrderId"] = orderId;
                return RedirectToAction("Create", "OrderDetails");
            }
            return View("Error");
        }


        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }
            var order = await _context.OrderDetail
                .Include(o => o.Order)
                .Include(o => o.Product)
                .Where(m => m.OrderId == id).ToListAsync();
                
            if (order == null)
            {
                return NotFound();
            }
            ViewBag.OrderId = id;

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var orderDetails = await _context.OrderDetail.Where(od => od.OrderId == id).ToListAsync();
            if(orderDetails != null)
            {
                foreach(var row in orderDetails)
                {
                    _context.OrderDetail.Remove(row);
                }    
            }

            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Order.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Order?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }

    }
}

SinusCsharp/Views/Carts/Confirmation.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SinusCsharp.styles.css" asp-append-version="true" />
    <link rel="icon" href="./images/sinus-logo-symbol - small.png">
    <title>Confirmation</title>
</head>
<body>
    <div>
        <h2>Tack för din order! Den ligger snart i brevlådan</h2>
    </div>
    <a class="btn btn-primary" asp-controller="home" asp-action="index">Back to homepage</a>
</body>
</html>

SinusCsharp/Views/Carts/Delete.cshtml
@model SinusCsharp.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SinusCsharp/Views/Carts/Edit.cshtml
@model SinusCsharp.Models.Cart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h3>Cart</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <input type="hidden" asp-for="ProductId" class="form-control" />
                <h4>ProductId = @Model.ProductId</h4>

            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SinusCsharp/Views/Carts/Index.cshtml
@model IEnumerable<SinusCsharp.Models.Cart>

@{
    ViewData["Title"] = "Cart";
}

<h1>Products In Cart</h1>

@if(Model.Count() == 0)
{
    <h3 class="text-danger"> Your Cart is empty! </h3>
} else
{
   <a class="btn btn-outline-success float-end" asp-controller="Customers" asp-action="CheckOut" >Go To Checkout</a>
}
<table class="table align-middle text-center">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Price)
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                 <img src="@item.Product.ImageURL" class="card-img-top" alt="..." 
                 style="max-height:3rem;max-width:3rem">
            </td>
            <td>
                 @Html.DisplayFor(modelItem => item.Product.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                 @item.Product.Price.ToString("C")
            </td>
            <td>
                    @((item.Product.Price * item.Quantity).ToString("C"))
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SinusCsharp/Views/Carts/Pay.cshtml
@model IEnumerable<SinusCsharp.Models.Cart>

@{
    ViewData["Title"] = "Cart";
}

<h1>Products In Cart</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Price)
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Product.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
                <td>
                    @(item.Product.Price * item.Quantity)
                </td>
                <td>

                    <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-success" asp-controller="Orders" asp-action="Create">Confirm</a>