SinusCsharp/Models/Product.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinusCsharp.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string ImageURL { get; set; }
        public string Color { get; set; }
        [Column(TypeName = "Money")]
        public decimal Price { get; set; }
        public string Description { get; set; }

        // setting default values here aswell
        public bool IsAvailable { get; set; } = true;
        public int Stock { get; set; } = 50;
        public List<OrderDetail>? Details { get; set; }        
    }
}

SinusCsharp/Controllers/CartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Data.Services;
using SinusCsharp.Models;


namespace SinusCsharp.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICartService _cartService;

        public CartsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor,
            ICartService cartService)
        {
            _cartService = cartService;
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Carts
        public IActionResult Index()
        {
            List<Cart>? cartList = new();
            if(HttpContext.Request.Cookies.ContainsKey("Cart")) 
            {
                var json = Request.Cookies["Cart"];
                cartList = JsonSerializer.Deserialize<List<Cart>>(json);
            } 

            return View(cartList);
        }

        // GET: Carts/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<Cart> cartList = GetCartListFromCookie();
            var item = cartList.FirstOrDefault(i => i.ProductId == id);
            
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ProductId,Quantity")] Cart cart)
        {
            if (id != cart.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                List<Cart> cartList = GetCartListFromCookie();
                cartList = _cartService.UpdateQuantityOfAProduct(cartList, cart);
                AddCartListToCookie(cartList);
  
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<Cart> cartList = GetCartListFromCookie();

            var cart = cartList.FirstOrDefault(m => m.ProductId == id);

            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            var cartList = GetCartListFromCookie();

            if (cartList != null)
            {
                cartList.RemoveAll(i => i.ProductId == id);
            }
            AddCartListToCookie(cartList);

            return RedirectToAction(nameof(Index));
        }

        //Get
        public IActionResult Buy(int id)
        {

            Product? product = _context.Product.FirstOrDefault(p => p.ProductId == id);

            Cart cartobject = new() { ProductId = id, Quantity = 1, Product = product };

            List<Cart>? cartList = GetCartListFromCookie();

            cartList = _cartService.AddProductToCart(cartList, cartobject);

            AddCartListToCookie(cartList);

            return RedirectToAction(nameof(Index));
        }
        //
        public IActionResult Pay(int customerId)
        {
            if (!HttpContext.Request.Cookies.ContainsKey("Customer"))
            {
                CookieOptions cookieCustomer = new CookieOptions();
                cookieCustomer.Expires = DateTime.UtcNow.AddMinutes(5);
                cookieCustomer.Path = "/"; //Also defaultvalue. Will be accessible "everywhere"

                // https://code-maze.com/csharp-object-into-json-string-dotnet/
                //var jsonString = JsonSerializer.Serialize(customerId);

                Response.Cookies.Append("Customer", customerId.ToString(), cookieCustomer);
           
            }
            List<Cart> cartList = GetCartListFromCookie();
            return View(cartList);
        }
        public IActionResult Confirmation()
        {
            // Get and send Customer,Order and Productlist to view
            // Partialview only return the Confirmation view without the layout
            return PartialView();
        }


        public List<Cart> GetCartListFromCookie()
        {
            //Unserialize cartList from Cookie
            var json = Request.Cookies["Cart"];
            List<Cart>? cartList = JsonSerializer.Deserialize<List<Cart>>(json);
            return cartList;
        }
        private void AddCartListToCookie(List<Cart> cartList)
        {
            //Serialize new cartList
            var jsonString = JsonSerializer.Serialize(cartList);
            Response.Cookies.Append("Cart", jsonString);
        }



        // Not needed but nice example of try-catch specifik sqlException
        /*public async Task<IActionResult> Buy2(int id)
        {

            if (ModelState.IsValid)
            {
                Cart cart = new Cart() { ProductId = id, Quantity = 1};
                try
                {
                    _context.Add(cart);
                    await _context.SaveChangesAsync();  
                }
                catch (DbUpdateException ex) 
                {
                    if (ex.InnerException is SqlException sqlException)
                    {
                        // Check if the error code indicates a unique key constraint violation
                        if (sqlException.Number == 2627 || sqlException.Number == 2601)
                        {
                            //Only update the specifik field qty
                            var cartItem = _context.Cart.SingleOrDefault(x => x.ProductId == id);
                            int qty = cartItem.Quantity +1;
         
                            _context.Cart.Where(x => x.ProductId == id)
                                .ExecuteUpdate(q => q.SetProperty(p => p.Quantity, qty));
                        }
                        else
                        {
                            // Handle other SQL exceptions
                            // For example:
                            Console.WriteLine("An SQL exception occurred with error code " + sqlException.Number);
                        }
                    }

                }
                
            }
            return RedirectToAction("Index", "Products");
        } */
    }
}

SinusCsharp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Models;

namespace SinusCsharp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.Customer);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Orders/Create
        public async Task<IActionResult> Create()
        {
            //var id = Request.Cookies["Customer"];
            int customerId = int.Parse(Request.Cookies["Customer"]);
            if(customerId != 0)
            {
                Order order = new() {CustomerId = customerId, OrderDate = DateTime.Now, Shipped = true};
                _context.Add(order);
                await _context.SaveChangesAsync();
                int orderId = order.OrderId; //Get last inserted Id
                TempData["OrderId"] = orderId;
                return RedirectToAction("Create", "OrderDetails");
            }
            return View("Error");
        }


        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }
            var order = await _context.OrderDetail
                .Include(o => o.Order)
                .Include(o => o.Product)
                .Where(m => m.OrderId == id).ToListAsync();
                
            if (order == null)
            {
                return NotFound();
            }
            ViewBag.OrderId = id;

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var orderDetails = await _context.OrderDetail.Where(od => od.OrderId == id).ToListAsync();
            if(orderDetails != null)
            {
                foreach(var row in orderDetails)
                {
                    _context.OrderDetail.Remove(row);
                }    
            }

            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Order.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Order?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }

    }
}

SinusCsharp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SinusCsharp.Data;
using SinusCsharp.Models;

namespace SinusCsharp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {

            return _context.Product != null ? 
                          View(await _context.Product.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Product'  is null.");
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,ImageURL,Color,Price,Description,IsAvailable,Stock")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Title,ImageURL,Color,Price,Description,IsAvailable,Stock")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Product?.Any(e => e.ProductId == id)).GetValueOrDefault();
        }

        public IActionResult Ninja()
        {
            return View();
        }
    }
}

SinusCsharp/Views/Products/Create.cshtml
@model SinusCsharp.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="mx-auto col-10 col-md-8 col-lg-6">
        <form asp-action="Create">
            <div class="form-group text-center">
                <img id="ImageURLpreview" style="max-height: 200px"/>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group" style="margin-bottom: 1rem;">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-bottom: 1rem;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mx-auto col-10 col-md-8 col-lg-6">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        // this shows the picture if you input something wrong, so it stays there.
        $(document).ready(function (){
            var output = document.getElementById('ImageURLpreview');
            output.src = $("#ImageURL").val();
        })

        // this shows the picture when its added in the link
        $("#ImageURL").on("change", function ()
        {
            var output = document.getElementById('ImageURLpreview');
            output.src = $(this).val();
        });
    </script>
}

SinusCsharp/Views/Products/Delete.cshtml
@model SinusCsharp.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SinusCsharp/Views/Products/Details.cshtml
@model SinusCsharp.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductId">Edit</a> |
    <a asp-controller="Carts" asp-action="Buy" asp-route-id="@Model?.ProductId">Buy</a> |
    <a asp-action="Index">Back to List</a>
</div>

SinusCsharp/Views/Products/Edit.cshtml
@model SinusCsharp.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SinusCsharp/Views/Products/Index.cshtml
@model IEnumerable<SinusCsharp.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<div class="row">

    @foreach (var item in Model) {
         

        <div class="card" style="width: 18rem;margin: 1rem">
            <img src="@item.ImageURL" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"> @item.Title</h5>
                <p class="card-text">@item.Color</p>
                <p class="card-text">@item.Price</p>
                <p class="card-text">@item.Description</p>
                <a class="btn btn-primary" asp-controller="Carts" asp-action="Buy" asp-route-id="@item.ProductId">Add To Cart</a>
            </div>
            <div>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>      
            </div>
        </div>
    }
</div>




            
 

SinusCsharp/Views/Products/Index2.cshtml
@model IEnumerable<SinusCsharp.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            @*<form asp-controller="Orders" asp-action="Buy">*@
               
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a> |
                <a asp-controller="Carts" asp-action="Buy" asp-route-id="@item.ProductId">Buy</a>
                @*<a asp-controller="Orders" asp-action="Buy" asp-route-id="@item.ProductId">Buy</a>*@
                   @*<form asp-controller="Orders" asp-action="Buy">*@
                 @*<input type="hidden" value="@item.ProductId"/>
                 <input type="submit" value="Buy"/>*@
                @*   </form>*@
            </td>
        </tr>
            @*</form>*@
        }
    </tbody>
</table>